### PR TITLE
Sensorify

### PR DESCRIPTION
**Pull request by ladyada**
big refactor, add SPI support, helper functions, Adafruit Sensor subclassed, etc.

### CODE REVIEW

**Comment by caternuson** [comment]
Cool. Yah, was wanting to follow up with some of this also after doing #9. 

How did you wire for SPI? CS pin in particular.

**Comment by ladyada** [comment]
CS goes to pin 10

**Comment by caternuson** [comment]
I2C works great. But SPI not working. [The guide](https://learn.adafruit.com/mlx90393-wide-range-3-axis-magnetometer/pinout) mentions SPI not working with current PCB layout? Or am I just wired wrong?

- 3V to 3V
- GND to GND
- SCK to SCL
- MOSI to SDA
- MISO to MIS
- D10 to CS

mlx_spi_test

Running new example with this change:
```cpp
  //if (! sensor.begin_I2C()) {          // hardware I2C mode, can pass in address & alt Wire
  if (! sensor.begin_SPI(MLX90393_CS)) {  // hardware SPI mode
```

Screenshot from 2020-10-11 11-00-57

**Comment by ladyada** [comment]
i dont have one of the old-style ones so i cant test that. i tested with new design and it works

**Comment by caternuson** [comment]
OK, mine dates from April 2019. I guess I2C is all I can test for now.

**Review by caternuson — APPROVED** [review]

**Pull request merged**
